repos:
- repo: https://github.com/prettier/prettier
  rev: "2.1.2" # Use the sha or tag you want to point at
  hooks:
    - id: prettier
      files: 'Frontend/.*'
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
    - id: black
      files: 'Server/.*'
      language_version: python3.8