ARG CSD_DOCKER_REGISTRY
ARG CSD_PROJECT_NAME
ARG CSD_DOCKER_LOCAL_TAG


#########################
# dev stage
#########################
# 
FROM ${CSD_DOCKER_REGISTRY}/${CSD_PROJECT_NAME}-webapp-server-proxy:${CSD_DOCKER_LOCAL_TAG}-base
# 

COPY ./conf/docker/webapp/server/proxy/start_dev.sh /start.sh
RUN sed -i 's/\r//' /start.sh
RUN chmod +x /start.sh

# copy the nginx conf file
COPY ./conf/docker/webapp/server/proxy/nginx_dev.conf /etc/nginx/conf.d/nginx.tmpl
CMD /bin/bash -c "/start.sh >/var/log/docker/stdout 2>/var/log/docker/stderr"
